rom_config: '../../Output/config.yaml'
build_path: '../../Delink'
delinks_path: '../../Delink/delinks'
main_module:
  name: main
  object: '../../Delink/build/arm9.bin'
  hash: '034256ac006fe32c'
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../Delink/build/itcm.bin'
  hash: c67897cb83356e59
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../Delink/build/dtcm.bin'
  hash: '67b701b46384bf50'
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays:
- id: 0
  name: ov000
  object: '../../Delink/build/arm9_ov000.bin'
  hash: '842941dcb78c99ae'
  delinks: overlays/ov000/delinks.txt
  symbols: overlays/ov000/symbols.txt
  relocations: overlays/ov000/relocs.txt
- id: 1
  name: ov001
  object: '../../Delink/build/arm9_ov001.bin'
  hash: '10f08c0da7852fb3'
  delinks: overlays/ov001/delinks.txt
  symbols: overlays/ov001/symbols.txt
  relocations: overlays/ov001/relocs.txt
- id: 2
  name: ov002
  object: '../../Delink/build/arm9_ov002.bin'
  hash: c7a70819ca520e10
  delinks: overlays/ov002/delinks.txt
  symbols: overlays/ov002/symbols.txt
  relocations: overlays/ov002/relocs.txt
- id: 3
  name: ov003
  object: '../../Delink/build/arm9_ov003.bin'
  hash: f3388462fcdbada0
  delinks: overlays/ov003/delinks.txt
  symbols: overlays/ov003/symbols.txt
  relocations: overlays/ov003/relocs.txt
- id: 4
  name: ov004
  object: '../../Delink/build/arm9_ov004.bin'
  hash: ce4e498ddef1df52
  delinks: overlays/ov004/delinks.txt
  symbols: overlays/ov004/symbols.txt
  relocations: overlays/ov004/relocs.txt
- id: 5
  name: ov005
  object: '../../Delink/build/arm9_ov005.bin'
  hash: a3a7496a702cf09f
  delinks: overlays/ov005/delinks.txt
  symbols: overlays/ov005/symbols.txt
  relocations: overlays/ov005/relocs.txt
- id: 6
  name: ov006
  object: '../../Delink/build/arm9_ov006.bin'
  hash: '68a39affc7869c8c'
  delinks: overlays/ov006/delinks.txt
  symbols: overlays/ov006/symbols.txt
  relocations: overlays/ov006/relocs.txt
- id: 7
  name: ov007
  object: '../../Delink/build/arm9_ov007.bin'
  hash: '439f1571091240c7'
  delinks: overlays/ov007/delinks.txt
  symbols: overlays/ov007/symbols.txt
  relocations: overlays/ov007/relocs.txt
- id: 8
  name: ov008
  object: '../../Delink/build/arm9_ov008.bin'
  hash: '39065a28c8a8ef17'
  delinks: overlays/ov008/delinks.txt
  symbols: overlays/ov008/symbols.txt
  relocations: overlays/ov008/relocs.txt
- id: 9
  name: ov009
  object: '../../Delink/build/arm9_ov009.bin'
  hash: '9b12ef8d04fa89d4'
  delinks: overlays/ov009/delinks.txt
  symbols: overlays/ov009/symbols.txt
  relocations: overlays/ov009/relocs.txt
- id: 10
  name: ov010
  object: '../../Delink/build/arm9_ov010.bin'
  hash: '848db76e8c6f4c80'
  delinks: overlays/ov010/delinks.txt
  symbols: overlays/ov010/symbols.txt
  relocations: overlays/ov010/relocs.txt
- id: 11
  name: ov011
  object: '../../Delink/build/arm9_ov011.bin'
  hash: '048575d87b09dbcb'
  delinks: overlays/ov011/delinks.txt
  symbols: overlays/ov011/symbols.txt
  relocations: overlays/ov011/relocs.txt
- id: 12
  name: ov012
  object: '../../Delink/build/arm9_ov012.bin'
  hash: ac682413d06147b1
  delinks: overlays/ov012/delinks.txt
  symbols: overlays/ov012/symbols.txt
  relocations: overlays/ov012/relocs.txt
- id: 13
  name: ov013
  object: '../../Delink/build/arm9_ov013.bin'
  hash: f90c51658d78c301
  delinks: overlays/ov013/delinks.txt
  symbols: overlays/ov013/symbols.txt
  relocations: overlays/ov013/relocs.txt
- id: 14
  name: ov014
  object: '../../Delink/build/arm9_ov014.bin'
  hash: '172d0377b19fd478'
  delinks: overlays/ov014/delinks.txt
  symbols: overlays/ov014/symbols.txt
  relocations: overlays/ov014/relocs.txt
- id: 15
  name: ov015
  object: '../../Delink/build/arm9_ov015.bin'
  hash: '9cf6dbbee927d285'
  delinks: overlays/ov015/delinks.txt
  symbols: overlays/ov015/symbols.txt
  relocations: overlays/ov015/relocs.txt
- id: 16
  name: ov016
  object: '../../Delink/build/arm9_ov016.bin'
  hash: '9fb64f44366b0324'
  delinks: overlays/ov016/delinks.txt
  symbols: overlays/ov016/symbols.txt
  relocations: overlays/ov016/relocs.txt
- id: 17
  name: ov017
  object: '../../Delink/build/arm9_ov017.bin'
  hash: cdbe505245cf35c3
  delinks: overlays/ov017/delinks.txt
  symbols: overlays/ov017/symbols.txt
  relocations: overlays/ov017/relocs.txt
- id: 18
  name: ov018
  object: '../../Delink/build/arm9_ov018.bin'
  hash: '556d518f90a182b9'
  delinks: overlays/ov018/delinks.txt
  symbols: overlays/ov018/symbols.txt
  relocations: overlays/ov018/relocs.txt
- id: 19
  name: ov019
  object: '../../Delink/build/arm9_ov019.bin'
  hash: '017c336ca51b3c58'
  delinks: overlays/ov019/delinks.txt
  symbols: overlays/ov019/symbols.txt
  relocations: overlays/ov019/relocs.txt
- id: 20
  name: ov020
  object: '../../Delink/build/arm9_ov020.bin'
  hash: ef6418b755b1f647
  delinks: overlays/ov020/delinks.txt
  symbols: overlays/ov020/symbols.txt
  relocations: overlays/ov020/relocs.txt
- id: 21
  name: ov021
  object: '../../Delink/build/arm9_ov021.bin'
  hash: '1799b648946d018b'
  delinks: overlays/ov021/delinks.txt
  symbols: overlays/ov021/symbols.txt
  relocations: overlays/ov021/relocs.txt
- id: 22
  name: ov022
  object: '../../Delink/build/arm9_ov022.bin'
  hash: '82350688acbd91ba'
  delinks: overlays/ov022/delinks.txt
  symbols: overlays/ov022/symbols.txt
  relocations: overlays/ov022/relocs.txt
- id: 23
  name: ov023
  object: '../../Delink/build/arm9_ov023.bin'
  hash: '13f5f80e03895a40'
  delinks: overlays/ov023/delinks.txt
  symbols: overlays/ov023/symbols.txt
  relocations: overlays/ov023/relocs.txt
- id: 24
  name: ov024
  object: '../../Delink/build/arm9_ov024.bin'
  hash: '3d36a15793975881'
  delinks: overlays/ov024/delinks.txt
  symbols: overlays/ov024/symbols.txt
  relocations: overlays/ov024/relocs.txt
- id: 25
  name: ov025
  object: '../../Delink/build/arm9_ov025.bin'
  hash: '2ea649213c5e6056'
  delinks: overlays/ov025/delinks.txt
  symbols: overlays/ov025/symbols.txt
  relocations: overlays/ov025/relocs.txt
- id: 26
  name: ov026
  object: '../../Delink/build/arm9_ov026.bin'
  hash: '96bbd4a7f4acbc3d'
  delinks: overlays/ov026/delinks.txt
  symbols: overlays/ov026/symbols.txt
  relocations: overlays/ov026/relocs.txt
- id: 27
  name: ov027
  object: '../../Delink/build/arm9_ov027.bin'
  hash: '63f3c63e35fe3e0e'
  delinks: overlays/ov027/delinks.txt
  symbols: overlays/ov027/symbols.txt
  relocations: overlays/ov027/relocs.txt
- id: 28
  name: ov028
  object: '../../Delink/build/arm9_ov028.bin'
  hash: f070cb0619625dc9
  delinks: overlays/ov028/delinks.txt
  symbols: overlays/ov028/symbols.txt
  relocations: overlays/ov028/relocs.txt
- id: 29
  name: ov029
  object: '../../Delink/build/arm9_ov029.bin'
  hash: '5570927dffcac105'
  delinks: overlays/ov029/delinks.txt
  symbols: overlays/ov029/symbols.txt
  relocations: overlays/ov029/relocs.txt
- id: 30
  name: ov030
  object: '../../Delink/build/arm9_ov030.bin'
  hash: dacc7cb5dccea1a9
  delinks: overlays/ov030/delinks.txt
  symbols: overlays/ov030/symbols.txt
  relocations: overlays/ov030/relocs.txt
- id: 31
  name: ov031
  object: '../../Delink/build/arm9_ov031.bin'
  hash: d3e4170d20a4afb0
  delinks: overlays/ov031/delinks.txt
  symbols: overlays/ov031/symbols.txt
  relocations: overlays/ov031/relocs.txt
- id: 32
  name: ov032
  object: '../../Delink/build/arm9_ov032.bin'
  hash: ceeca27cf0e60ee2
  delinks: overlays/ov032/delinks.txt
  symbols: overlays/ov032/symbols.txt
  relocations: overlays/ov032/relocs.txt
- id: 33
  name: ov033
  object: '../../Delink/build/arm9_ov033.bin'
  hash: '03a6825cbb695914'
  delinks: overlays/ov033/delinks.txt
  symbols: overlays/ov033/symbols.txt
  relocations: overlays/ov033/relocs.txt
- id: 34
  name: ov034
  object: '../../Delink/build/arm9_ov034.bin'
  hash: ee1ba0b42ca10975
  delinks: overlays/ov034/delinks.txt
  symbols: overlays/ov034/symbols.txt
  relocations: overlays/ov034/relocs.txt
- id: 35
  name: ov035
  object: '../../Delink/build/arm9_ov035.bin'
  hash: '3f405571926fa104'
  delinks: overlays/ov035/delinks.txt
  symbols: overlays/ov035/symbols.txt
  relocations: overlays/ov035/relocs.txt
- id: 36
  name: ov036
  object: '../../Delink/build/arm9_ov036.bin'
  hash: '7a8f42cb4faaa0ee'
  delinks: overlays/ov036/delinks.txt
  symbols: overlays/ov036/symbols.txt
  relocations: overlays/ov036/relocs.txt
- id: 37
  name: ov037
  object: '../../Delink/build/arm9_ov037.bin'
  hash: '429b7eb8acac3e19'
  delinks: overlays/ov037/delinks.txt
  symbols: overlays/ov037/symbols.txt
  relocations: overlays/ov037/relocs.txt
- id: 38
  name: ov038
  object: '../../Delink/build/arm9_ov038.bin'
  hash: '628eb8be238370a2'
  delinks: overlays/ov038/delinks.txt
  symbols: overlays/ov038/symbols.txt
  relocations: overlays/ov038/relocs.txt
- id: 39
  name: ov039
  object: '../../Delink/build/arm9_ov039.bin'
  hash: '6be669872cf89c1c'
  delinks: overlays/ov039/delinks.txt
  symbols: overlays/ov039/symbols.txt
  relocations: overlays/ov039/relocs.txt
- id: 40
  name: ov040
  object: '../../Delink/build/arm9_ov040.bin'
  hash: '403f12ecc1ff7502'
  delinks: overlays/ov040/delinks.txt
  symbols: overlays/ov040/symbols.txt
  relocations: overlays/ov040/relocs.txt
- id: 41
  name: ov041
  object: '../../Delink/build/arm9_ov041.bin'
  hash: d98f4aaffb8d08b9
  delinks: overlays/ov041/delinks.txt
  symbols: overlays/ov041/symbols.txt
  relocations: overlays/ov041/relocs.txt
- id: 42
  name: ov042
  object: '../../Delink/build/arm9_ov042.bin'
  hash: '927d835f65669059'
  delinks: overlays/ov042/delinks.txt
  symbols: overlays/ov042/symbols.txt
  relocations: overlays/ov042/relocs.txt
- id: 43
  name: ov043
  object: '../../Delink/build/arm9_ov043.bin'
  hash: '9da5e19f0c14869b'
  delinks: overlays/ov043/delinks.txt
  symbols: overlays/ov043/symbols.txt
  relocations: overlays/ov043/relocs.txt
- id: 44
  name: ov044
  object: '../../Delink/build/arm9_ov044.bin'
  hash: '4dcee9564197665e'
  delinks: overlays/ov044/delinks.txt
  symbols: overlays/ov044/symbols.txt
  relocations: overlays/ov044/relocs.txt
- id: 45
  name: ov045
  object: '../../Delink/build/arm9_ov045.bin'
  hash: '00bede122a0434f7'
  delinks: overlays/ov045/delinks.txt
  symbols: overlays/ov045/symbols.txt
  relocations: overlays/ov045/relocs.txt
- id: 46
  name: ov046
  object: '../../Delink/build/arm9_ov046.bin'
  hash: '0db41eb5a1b4ff19'
  delinks: overlays/ov046/delinks.txt
  symbols: overlays/ov046/symbols.txt
  relocations: overlays/ov046/relocs.txt
- id: 47
  name: ov047
  object: '../../Delink/build/arm9_ov047.bin'
  hash: a02fb2104df6263d
  delinks: overlays/ov047/delinks.txt
  symbols: overlays/ov047/symbols.txt
  relocations: overlays/ov047/relocs.txt
- id: 48
  name: ov048
  object: '../../Delink/build/arm9_ov048.bin'
  hash: '492ef546f9f54cce'
  delinks: overlays/ov048/delinks.txt
  symbols: overlays/ov048/symbols.txt
  relocations: overlays/ov048/relocs.txt
- id: 49
  name: ov049
  object: '../../Delink/build/arm9_ov049.bin'
  hash: '6b6da538ee3c26fc'
  delinks: overlays/ov049/delinks.txt
  symbols: overlays/ov049/symbols.txt
  relocations: overlays/ov049/relocs.txt
- id: 50
  name: ov050
  object: '../../Delink/build/arm9_ov050.bin'
  hash: '557a58472a1c91bc'
  delinks: overlays/ov050/delinks.txt
  symbols: overlays/ov050/symbols.txt
  relocations: overlays/ov050/relocs.txt
- id: 51
  name: ov051
  object: '../../Delink/build/arm9_ov051.bin'
  hash: b2abb4b44faa9f29
  delinks: overlays/ov051/delinks.txt
  symbols: overlays/ov051/symbols.txt
  relocations: overlays/ov051/relocs.txt
- id: 52
  name: ov052
  object: '../../Delink/build/arm9_ov052.bin'
  hash: '3c8aefa001e0f467'
  delinks: overlays/ov052/delinks.txt
  symbols: overlays/ov052/symbols.txt
  relocations: overlays/ov052/relocs.txt
- id: 53
  name: ov053
  object: '../../Delink/build/arm9_ov053.bin'
  hash: b5483f3f4ce36be0
  delinks: overlays/ov053/delinks.txt
  symbols: overlays/ov053/symbols.txt
  relocations: overlays/ov053/relocs.txt
- id: 54
  name: ov054
  object: '../../Delink/build/arm9_ov054.bin'
  hash: dfabdeecd1493dc2
  delinks: overlays/ov054/delinks.txt
  symbols: overlays/ov054/symbols.txt
  relocations: overlays/ov054/relocs.txt
- id: 55
  name: ov055
  object: '../../Delink/build/arm9_ov055.bin'
  hash: '7e53cd6aadd55f66'
  delinks: overlays/ov055/delinks.txt
  symbols: overlays/ov055/symbols.txt
  relocations: overlays/ov055/relocs.txt
- id: 56
  name: ov056
  object: '../../Delink/build/arm9_ov056.bin'
  hash: '64a8a94475edf054'
  delinks: overlays/ov056/delinks.txt
  symbols: overlays/ov056/symbols.txt
  relocations: overlays/ov056/relocs.txt
- id: 57
  name: ov057
  object: '../../Delink/build/arm9_ov057.bin'
  hash: '25dd47218243b110'
  delinks: overlays/ov057/delinks.txt
  symbols: overlays/ov057/symbols.txt
  relocations: overlays/ov057/relocs.txt
- id: 58
  name: ov058
  object: '../../Delink/build/arm9_ov058.bin'
  hash: f1839b49fd1865ed
  delinks: overlays/ov058/delinks.txt
  symbols: overlays/ov058/symbols.txt
  relocations: overlays/ov058/relocs.txt
- id: 59
  name: ov059
  object: '../../Delink/build/arm9_ov059.bin'
  hash: e0a6cd8a4f87c23a
  delinks: overlays/ov059/delinks.txt
  symbols: overlays/ov059/symbols.txt
  relocations: overlays/ov059/relocs.txt
- id: 60
  name: ov060
  object: '../../Delink/build/arm9_ov060.bin'
  hash: '4cac178bc734d133'
  delinks: overlays/ov060/delinks.txt
  symbols: overlays/ov060/symbols.txt
  relocations: overlays/ov060/relocs.txt
- id: 61
  name: ov061
  object: '../../Delink/build/arm9_ov061.bin'
  hash: bbe2db1b9eba578b
  delinks: overlays/ov061/delinks.txt
  symbols: overlays/ov061/symbols.txt
  relocations: overlays/ov061/relocs.txt
- id: 62
  name: ov062
  object: '../../Delink/build/arm9_ov062.bin'
  hash: '3378e46bf67f6641'
  delinks: overlays/ov062/delinks.txt
  symbols: overlays/ov062/symbols.txt
  relocations: overlays/ov062/relocs.txt
- id: 63
  name: ov063
  object: '../../Delink/build/arm9_ov063.bin'
  hash: a5ca15194c6c09cd
  delinks: overlays/ov063/delinks.txt
  symbols: overlays/ov063/symbols.txt
  relocations: overlays/ov063/relocs.txt
- id: 64
  name: ov064
  object: '../../Delink/build/arm9_ov064.bin'
  hash: '2bd13961e843b25d'
  delinks: overlays/ov064/delinks.txt
  symbols: overlays/ov064/symbols.txt
  relocations: overlays/ov064/relocs.txt
- id: 65
  name: ov065
  object: '../../Delink/build/arm9_ov065.bin'
  hash: '744a8dbc6bd96abb'
  delinks: overlays/ov065/delinks.txt
  symbols: overlays/ov065/symbols.txt
  relocations: overlays/ov065/relocs.txt
- id: 66
  name: ov066
  object: '../../Delink/build/arm9_ov066.bin'
  hash: '81cf5ab9cc068d8e'
  delinks: overlays/ov066/delinks.txt
  symbols: overlays/ov066/symbols.txt
  relocations: overlays/ov066/relocs.txt
- id: 67
  name: ov067
  object: '../../Delink/build/arm9_ov067.bin'
  hash: '988405294932c051'
  delinks: overlays/ov067/delinks.txt
  symbols: overlays/ov067/symbols.txt
  relocations: overlays/ov067/relocs.txt
- id: 68
  name: ov068
  object: '../../Delink/build/arm9_ov068.bin'
  hash: b6c6700f2574dcad
  delinks: overlays/ov068/delinks.txt
  symbols: overlays/ov068/symbols.txt
  relocations: overlays/ov068/relocs.txt
- id: 69
  name: ov069
  object: '../../Delink/build/arm9_ov069.bin'
  hash: d37d3682cf3cd1e8
  delinks: overlays/ov069/delinks.txt
  symbols: overlays/ov069/symbols.txt
  relocations: overlays/ov069/relocs.txt
- id: 70
  name: ov070
  object: '../../Delink/build/arm9_ov070.bin'
  hash: '8b3808d9c9034060'
  delinks: overlays/ov070/delinks.txt
  symbols: overlays/ov070/symbols.txt
  relocations: overlays/ov070/relocs.txt
- id: 71
  name: ov071
  object: '../../Delink/build/arm9_ov071.bin'
  hash: '6acb097d92c70870'
  delinks: overlays/ov071/delinks.txt
  symbols: overlays/ov071/symbols.txt
  relocations: overlays/ov071/relocs.txt
- id: 72
  name: ov072
  object: '../../Delink/build/arm9_ov072.bin'
  hash: b849b30c16e92fba
  delinks: overlays/ov072/delinks.txt
  symbols: overlays/ov072/symbols.txt
  relocations: overlays/ov072/relocs.txt
- id: 73
  name: ov073
  object: '../../Delink/build/arm9_ov073.bin'
  hash: '807575af8a9b83fc'
  delinks: overlays/ov073/delinks.txt
  symbols: overlays/ov073/symbols.txt
  relocations: overlays/ov073/relocs.txt
- id: 74
  name: ov074
  object: '../../Delink/build/arm9_ov074.bin'
  hash: e86b309ec3b6f298
  delinks: overlays/ov074/delinks.txt
  symbols: overlays/ov074/symbols.txt
  relocations: overlays/ov074/relocs.txt
- id: 75
  name: ov075
  object: '../../Delink/build/arm9_ov075.bin'
  hash: '4f1753994bed1a4b'
  delinks: overlays/ov075/delinks.txt
  symbols: overlays/ov075/symbols.txt
  relocations: overlays/ov075/relocs.txt
- id: 76
  name: ov076
  object: '../../Delink/build/arm9_ov076.bin'
  hash: '9bc1d5943468ab5d'
  delinks: overlays/ov076/delinks.txt
  symbols: overlays/ov076/symbols.txt
  relocations: overlays/ov076/relocs.txt
- id: 77
  name: ov077
  object: '../../Delink/build/arm9_ov077.bin'
  hash: e99210929a2ac984
  delinks: overlays/ov077/delinks.txt
  symbols: overlays/ov077/symbols.txt
  relocations: overlays/ov077/relocs.txt
- id: 78
  name: ov078
  object: '../../Delink/build/arm9_ov078.bin'
  hash: a000b50c075aea80
  delinks: overlays/ov078/delinks.txt
  symbols: overlays/ov078/symbols.txt
  relocations: overlays/ov078/relocs.txt
- id: 79
  name: ov079
  object: '../../Delink/build/arm9_ov079.bin'
  hash: ccf17d30737803b5
  delinks: overlays/ov079/delinks.txt
  symbols: overlays/ov079/symbols.txt
  relocations: overlays/ov079/relocs.txt
- id: 80
  name: ov080
  object: '../../Delink/build/arm9_ov080.bin'
  hash: '5fcb57b726f26fd3'
  delinks: overlays/ov080/delinks.txt
  symbols: overlays/ov080/symbols.txt
  relocations: overlays/ov080/relocs.txt
- id: 81
  name: ov081
  object: '../../Delink/build/arm9_ov081.bin'
  hash: a51a4787ab016745
  delinks: overlays/ov081/delinks.txt
  symbols: overlays/ov081/symbols.txt
  relocations: overlays/ov081/relocs.txt
- id: 82
  name: ov082
  object: '../../Delink/build/arm9_ov082.bin'
  hash: '6cde8db3872af35b'
  delinks: overlays/ov082/delinks.txt
  symbols: overlays/ov082/symbols.txt
  relocations: overlays/ov082/relocs.txt
- id: 83
  name: ov083
  object: '../../Delink/build/arm9_ov083.bin'
  hash: ff74aca341d31b1b
  delinks: overlays/ov083/delinks.txt
  symbols: overlays/ov083/symbols.txt
  relocations: overlays/ov083/relocs.txt
- id: 84
  name: ov084
  object: '../../Delink/build/arm9_ov084.bin'
  hash: c5da8d59924fbb26
  delinks: overlays/ov084/delinks.txt
  symbols: overlays/ov084/symbols.txt
  relocations: overlays/ov084/relocs.txt
- id: 85
  name: ov085
  object: '../../Delink/build/arm9_ov085.bin'
  hash: '4dae65818b93ce56'
  delinks: overlays/ov085/delinks.txt
  symbols: overlays/ov085/symbols.txt
  relocations: overlays/ov085/relocs.txt
- id: 86
  name: ov086
  object: '../../Delink/build/arm9_ov086.bin'
  hash: b95ef5652152b95a
  delinks: overlays/ov086/delinks.txt
  symbols: overlays/ov086/symbols.txt
  relocations: overlays/ov086/relocs.txt
- id: 87
  name: ov087
  object: '../../Delink/build/arm9_ov087.bin'
  hash: '8813aaa181b60351'
  delinks: overlays/ov087/delinks.txt
  symbols: overlays/ov087/symbols.txt
  relocations: overlays/ov087/relocs.txt
- id: 88
  name: ov088
  object: '../../Delink/build/arm9_ov088.bin'
  hash: '7b44fc2b3632cba1'
  delinks: overlays/ov088/delinks.txt
  symbols: overlays/ov088/symbols.txt
  relocations: overlays/ov088/relocs.txt
- id: 89
  name: ov089
  object: '../../Delink/build/arm9_ov089.bin'
  hash: '1ff270716c40413a'
  delinks: overlays/ov089/delinks.txt
  symbols: overlays/ov089/symbols.txt
  relocations: overlays/ov089/relocs.txt
- id: 90
  name: ov090
  object: '../../Delink/build/arm9_ov090.bin'
  hash: '74d28760a565c6f8'
  delinks: overlays/ov090/delinks.txt
  symbols: overlays/ov090/symbols.txt
  relocations: overlays/ov090/relocs.txt
